name: Build Electron App

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      target:
        description: "Select what to build"
        required: true
        default: all
        type: choice
        options:
          - all
          - linux
          - windows
          - mac-x64
          - mac-arm64

jobs:
  linux:
    if: github.event_name == 'push' || github.event.inputs.target == 'linux' || github.event.inputs.target == 'all'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build (Linux)
        run: npm run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-linux
          path: dist/*

  windows:
    if: github.event_name == 'push' || github.event.inputs.target == 'windows' || github.event.inputs.target == 'all'
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build (Windows)
        run: npm run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-windows
          path: dist/*

  mac-x64:
    name: macOS x64 (Intel)
    if: github.event_name == 'push' || github.event.inputs.target == 'mac-x64' || github.event.inputs.target == 'all'
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build (macOS x64)
        run: npm run build -- --mac --x64

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-macos-x64
          path: dist/*

  mac-arm64:
    name: macOS arm64 (Apple Silicon)
    if: github.event_name == 'push' || github.event.inputs.target == 'mac-arm64' || github.event.inputs.target == 'all'
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build (macOS arm64)
        run: npm run build -- --mac --arm64

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-macos-arm64
          path: dist/*
